language: php

php:
  - 7.1

install:
  # install composer dependencies
  - composer install

script:
  # check coding standard (defined in composer.json "scripts" section)
  - composer check-cs
  # check with phpstan (defined in composer.json "scripts" section)
  - composer phpstan
  # run tests
  - vendor/bin/phpunit

# do not send success notifications, they have no value
notifications:
  email:
    on_success: never
